"""Record the schema ``1.3`` golden (index sets, parameters, families, templates).

Recorded *after* the templates were implemented, from the working tree
``c69f704`` plus the schema 1.3 changes (spec §14.15). It freezes what the
code does today for a fixed list of ``"version": "1.3"`` template problems
and for a fixed list of documents the expansion refuses, so a later change
cannot move either unnoticed; it does not prove that output correct -- spec
§14.16 and the ``test_template_*`` modules do that (the equivalence tests
hold every expansion against a hand-written explicit oracle). The lists are
spelled out here on purpose (no discovery), every problem is ``1.3``:

* ``examples/tsp_template.json`` (the schema 1.3 example, optimum 8);
* four fixtures of ``tests/fixtures/templates``: the assignment (a 0/1
  parameter in ``where`` leaves ``x[alice,drive]`` unused, so it is left
  out: ``UNUSED_TEMPLATE_VARIABLES``), the shift roster (the rest rule's
  outer index is used only in its member's ``where``), the two-worker
  window (a ``linear`` day set: ``TEMPLATE_BOUNDARY_SKIPPED`` for a
  quadratic term template and a constraint template) and the mixed problem
  (explicit entries naming generated variables, an integer family, a soft
  template whose rhs and weight are parameters, a cardinality rhs that is a
  parameter);
* five problems written for this golden: a ``cyclic`` ring of integer
  elements whose window template wraps onto itself
  (``TEMPLATE_TERMS_MERGED``), parameters as a cardinality rhs, a linear rhs
  and a soft weight, an integer family, soft templates only, and a family
  most of whose variables no template uses (``UNUSED_TEMPLATE_VARIABLES``
  with more names than it lists, plus ``EMPTY_TEMPLATE_EXPANSION``).

Each problem records these sections (see :data:`SECTIONS`):

``expanded``
    ``expand_problem(problem).problem.model_dump()``: the explicit entries
    first, then every generated one, in generation order.
``expansion_warnings``
    The expansion's own warnings as ``[code, path, message]``.
``snapshot``
    ``record_phase3a_golden.snapshot_problem`` of the expanded problem --
    both compiled models, the estimates and the penalty scale -- except that
    its two full validations are taken with
    ``validate_expanded(expand_problem(problem), ...)``, so every path on a
    generated entry is mapped back to its template and carries the
    ``(generated by ...)`` suffix, and the expansion warnings come first.
``exact_solve``
    ``OptimizationService.solve`` of the *template* problem (the service
    expands it) on the ``exact`` backend, for problems whose compiled BQM has
    at most 20 variables; null for the others. The fields kept and dropped
    are those of ``record_compat_golden.section_exact_solve`` (its helpers are
    imported and reused): nothing that changes between runs, machines or
    dependency versions.

A separate part, ``expansion_errors``, records what ``expand_problem``
reports, as ``[code, path, message]``, for documents it refuses (see
:data:`ERROR_DOCUMENTS`): each new error code of spec §14.10 at least once,
the version gate (``FEATURE_REQUIRES_NEWER_VERSION``) twice, both kinds of
``TEMPLATE_EXPANSION_LIMIT`` (the upper bound U and the work W, each under
an explicit small ``max_template_bindings`` so the golden does not follow
the policy default) and two documents whose errors pass the ceiling of 20
per source, so the ``... more errors ... are not listed`` suffix is frozen.

Recording refuses (raises) instead of writing a golden when a problem is not
``1.3``, when its expansion fails, when ``estimate_compiled_variables``
differs from the compiled BQM, when a problem with a known optimum solves to
another value, or when an error document expands without error.

Every value is a plain ``list`` / ``dict`` / ``str`` / ``float`` / ``int`` /
``bool`` / ``None`` so a ``json`` round-trip is exact. Re-record (only ever
intentionally) with::

    .venv/Scripts/python.exe tests/golden/record_schema_1_3_golden.py
"""

from __future__ import annotations

import copy
import json
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

from annealbridge.compiler import BQMCompiler
from annealbridge.models import OptimizationProblem
from annealbridge.orchestration import ExecutionPolicy, OptimizationService
from annealbridge.penalty.strategy import ScaledPenaltyStrategy
from annealbridge.validation import (
    DEFAULT_MAX_TEMPLATE_BINDINGS,
    ExpandedProblem,
    expand_problem,
    validate_expanded,
)
from annealbridge.validation.estimates import estimate_compiled_variables

# Run as a script only this file's directory is on ``sys.path``; the earlier
# goldens' helpers are imported as ``tests.golden...`` exactly as the test
# suite imports them, so the repository root has to be importable too.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from tests.golden.record_compat_golden import (
    _ATTEMPT_FIELDS,
    _EVALUATION_FIELDS,
    _METADATA_FIELDS,
    _SOLUTION_FIELDS,
    EXACT_MAX_BQM_VARIABLES,
    _code_path,
    _infeasibility,
    _load_example,
    _local_registry,
    _merge,
    _pick,
)
from tests.golden.record_phase3a_golden import _exact_capabilities, snapshot_problem

GOLDEN_PATH = Path(__file__).resolve().parent / "schema_1_3_expand.json"
FIXTURES_DIR = _REPO_ROOT / "tests" / "fixtures" / "templates"
RECORDED_FROM = "c69f704+schema-1.3"
VERSION = "1.3"


# --------------------------------------------------------------------------
# Problem builders. Each entry of PROBLEMS is a zero-argument callable that
# builds one ``1.3`` problem; the key is its stable name.
# --------------------------------------------------------------------------


def _load_fixture(name: str) -> OptimizationProblem:
    data = json.loads((FIXTURES_DIR / name).read_text(encoding="utf-8"))
    return OptimizationProblem.model_validate(data)


def _rows(indices: int, table: dict) -> list[dict]:
    """Parameter rows from ``{key: value}``; a one-index key is a bare element."""
    return [
        {"key": list(key) if indices > 1 else [key], "value": value}
        for key, value in table.items()
    ]


def make_problem_1_3(
    *,
    name: str,
    direction: str,
    index_sets: list[dict],
    variable_families: list[dict],
    parameters: list[dict] | None = None,
    variables: list[dict] | None = None,
    linear_term_templates: list[dict] | None = None,
    quadratic_term_templates: list[dict] | None = None,
    constraint_templates: list[dict] | None = None,
    cardinality_constraint_templates: list[dict] | None = None,
) -> OptimizationProblem:
    return OptimizationProblem.model_validate(
        {
            "version": VERSION,
            "name": name,
            "index_sets": index_sets,
            "parameters": parameters or [],
            "variable_families": variable_families,
            "variables": variables or [],
            "objective": {
                "direction": direction,
                "linear_terms": [],
                "linear_term_templates": linear_term_templates or [],
                "quadratic_term_templates": quadratic_term_templates or [],
            },
            "constraints": [],
            "constraint_templates": constraint_templates or [],
            "cardinality_constraint_templates": cardinality_constraint_templates or [],
            "solver": {"backend": "exact"},
        }
    )


def example_tsp_template() -> OptimizationProblem:
    return _load_example("tsp_template.json")


def fixture_assignment_template() -> OptimizationProblem:
    return _load_fixture("assignment_template.json")


def fixture_shift_template() -> OptimizationProblem:
    return _load_fixture("shift_template.json")


def fixture_window_template() -> OptimizationProblem:
    return _load_fixture("window_template.json")


def fixture_mixed_template() -> OptimizationProblem:
    return _load_fixture("mixed_template.json")


# Three nodes on a cyclic ring of integer elements (so the names read
# on[-1], on[0], on[1]); the window of four consecutive nodes wraps onto its
# own start, so every generated window names on[n] twice and the compiler
# sums it to 2*on[n] (TEMPLATE_TERMS_MERGED). Adjacent pairs cost 1.5, and
# the quadratic template wraps from on[1] to on[-1]. All three on breaks
# every window (4 > 3); of the rest, on[-1] and on[1] is best: 3 + 4 - 1.5 =
# 5.5, unique.
def ring_window_terms_merged() -> OptimizationProblem:
    return make_problem_1_3(
        name="ring_window_terms_merged",
        direction="maximize",
        index_sets=[{"name": "node", "elements": [-1, 0, 1], "order": "cyclic"}],
        parameters=[
            {"name": "gain", "indices": ["node"], "values": _rows(1, {-1: 3, 0: 2, 1: 4})}
        ],
        variable_families=[{"name": "on", "indices": ["node"]}],
        linear_term_templates=[
            {"for_each": ["n in node"], "coefficient": "gain[n]", "variable": "on[n]"}
        ],
        quadratic_term_templates=[
            {
                "for_each": ["n in node"],
                "coefficient": -1.5,
                "variable1": "on[n]",
                "variable2": "on[n+1]",
            }
        ],
        constraint_templates=[
            {
                "id": "window",
                "type": "hard",
                "for_each": ["n in node"],
                "terms": [
                    {"coefficient": 1, "variable": "on[n]"},
                    {"coefficient": 1, "variable": "on[n+1]"},
                    {"coefficient": 1, "variable": "on[n+2]"},
                    {"coefficient": 1, "variable": "on[n+3]"},
                ],
                "operator": "<=",
                "rhs": 3,
            }
        ],
    )


# Three tasks over two days. Parameters give a hard cardinality rhs (need),
# a hard linear rhs (cap) and a soft cardinality weight (urgency).
def parameter_rhs_and_weight() -> OptimizationProblem:
    return make_problem_1_3(
        name="parameter_rhs_and_weight",
        direction="minimize",
        index_sets=[
            {"name": "task", "elements": ["t1", "t2", "t3"]},
            {"name": "day", "elements": ["mon", "tue"]},
        ],
        parameters=[
            {
                "name": "cost",
                "indices": ["task", "day"],
                "values": _rows(
                    2,
                    {
                        ("t1", "mon"): 2,
                        ("t1", "tue"): 3,
                        ("t2", "mon"): 1,
                        ("t2", "tue"): 4,
                        ("t3", "mon"): 3,
                        ("t3", "tue"): 1,
                    },
                ),
            },
            {"name": "effort", "indices": ["task"], "values": _rows(1, {"t1": 1, "t2": 2, "t3": 1})},
            {"name": "need", "indices": ["day"], "values": _rows(1, {"mon": 2, "tue": 1})},
            {"name": "cap", "indices": ["day"], "values": _rows(1, {"mon": 3, "tue": 2})},
            {
                "name": "urgency",
                "indices": ["task"],
                "values": _rows(1, {"t1": 4, "t2": 2.5, "t3": 1}),
            },
        ],
        variable_families=[{"name": "do", "indices": ["task", "day"]}],
        linear_term_templates=[
            {
                "for_each": ["t in task", "d in day"],
                "coefficient": "cost[t,d]",
                "variable": "do[t,d]",
            }
        ],
        constraint_templates=[
            {
                "id": "effort_cap",
                "type": "hard",
                "for_each": ["d in day"],
                "terms": [
                    {"for_each": ["t in task"], "coefficient": "effort[t]", "variable": "do[t,d]"}
                ],
                "operator": "<=",
                "rhs": "cap[d]",
            }
        ],
        cardinality_constraint_templates=[
            {
                "id": "staffed",
                "type": "hard",
                "for_each": ["d in day"],
                "variables": [{"for_each": ["t in task"], "variable": "do[t,d]"}],
                "operator": "==",
                "rhs": "need[d]",
            },
            {
                "id": "done",
                "type": "soft",
                "for_each": ["t in task"],
                "variables": [{"for_each": ["d in day"], "variable": "do[t,d]"}],
                "operator": ">=",
                "rhs": 1,
                "weight": "urgency[t]",
            },
        ],
    )


# Integer units per product within an hour budget and a per-product cap
# (rhs a parameter), with diminishing returns (an integer self-product) and
# a binary open family linked to the units, each open product costing a
# fixed amount (a negative parameter value). p2's cap of 3 is its upper
# bound, so that generated constraint is REDUNDANT_CONSTRAINT.
def integer_family() -> OptimizationProblem:
    return make_problem_1_3(
        name="integer_family",
        direction="maximize",
        index_sets=[{"name": "product", "elements": ["p1", "p2"]}],
        parameters=[
            {"name": "profit", "indices": ["product"], "values": _rows(1, {"p1": 5, "p2": 3})},
            {"name": "hours", "indices": ["product"], "values": _rows(1, {"p1": 2, "p2": 1})},
            {"name": "max_units", "indices": ["product"], "values": _rows(1, {"p1": 2, "p2": 3})},
            {"name": "fixed", "indices": ["product"], "values": _rows(1, {"p1": -1, "p2": -2})},
        ],
        variable_families=[
            {
                "name": "units",
                "indices": ["product"],
                "type": "integer",
                "lower_bound": 0,
                "upper_bound": 3,
            },
            {"name": "open", "indices": ["product"], "type": "binary"},
        ],
        linear_term_templates=[
            {"for_each": ["p in product"], "coefficient": "profit[p]", "variable": "units[p]"},
            {"for_each": ["p in product"], "coefficient": "fixed[p]", "variable": "open[p]"},
        ],
        quadratic_term_templates=[
            {
                "for_each": ["p in product"],
                "coefficient": -0.5,
                "variable1": "units[p]",
                "variable2": "units[p]",
            }
        ],
        constraint_templates=[
            {
                "id": "hour_budget",
                "type": "hard",
                "terms": [
                    {"for_each": ["p in product"], "coefficient": "hours[p]", "variable": "units[p]"}
                ],
                "operator": "<=",
                "rhs": 5,
            },
            {
                "id": "unit_cap",
                "type": "hard",
                "for_each": ["p in product"],
                "terms": [{"coefficient": 1, "variable": "units[p]"}],
                "operator": "<=",
                "rhs": "max_units[p]",
            },
            {
                "id": "units_need_open",
                "type": "hard",
                "for_each": ["p in product"],
                "terms": [
                    {"coefficient": 1, "variable": "units[p]"},
                    {"coefficient": -3, "variable": "open[p]"},
                ],
                "operator": "<=",
                "rhs": 0,
            },
        ],
    )


# Soft templates only: a soft at-most-one over everyone (no for_each, so the
# generated id is the template id) and a soft "rather not" for the person a
# 0/1 parameter marks, with literal weights.
def soft_templates() -> OptimizationProblem:
    return make_problem_1_3(
        name="soft_templates",
        direction="maximize",
        index_sets=[{"name": "person", "elements": ["p1", "p2", "p3"]}],
        parameters=[
            {"name": "fun", "indices": ["person"], "values": _rows(1, {"p1": 3, "p2": 4, "p3": 2})},
            {
                "name": "dislike",
                "indices": ["person"],
                "default": 0,
                "values": _rows(1, {"p2": 1}),
            },
        ],
        variable_families=[{"name": "invite", "indices": ["person"]}],
        linear_term_templates=[
            {"for_each": ["p in person"], "coefficient": "fun[p]", "variable": "invite[p]"}
        ],
        constraint_templates=[
            {
                "id": "rather_not",
                "type": "soft",
                "for_each": ["p in person"],
                "where": ["dislike[p] == 1"],
                "terms": [{"coefficient": 1, "variable": "invite[p]"}],
                "operator": "<=",
                "rhs": 0,
                "weight": 1.5,
            }
        ],
        cardinality_constraint_templates=[
            {
                "id": "small_party",
                "type": "soft",
                "variables": [{"for_each": ["p in person"], "variable": "invite[p]"}],
                "operator": "<=",
                "rhs": 1,
                "weight": 2.5,
            }
        ],
    )


# A family over item x item of which only the pairs i < j are used (a
# position comparison in where): six of its nine variables are left out,
# more than the warning lists. The "same item" template's where never holds,
# so it generates nothing (EMPTY_TEMPLATE_EXPANSION).
def unused_family_variables() -> OptimizationProblem:
    return make_problem_1_3(
        name="unused_family_variables",
        direction="maximize",
        index_sets=[{"name": "item", "elements": ["a", "b", "c"]}],
        parameters=[
            {
                "name": "synergy",
                "indices": ["item", "item"],
                "values": _rows(2, {("a", "b"): 2, ("a", "c"): 3, ("b", "c"): 1}),
            }
        ],
        variable_families=[{"name": "pair", "indices": ["item", "item"]}],
        linear_term_templates=[
            {
                "for_each": ["i in item", "j in item"],
                "where": ["i < j"],
                "coefficient": "synergy[i,j]",
                "variable": "pair[i,j]",
            },
            {
                "for_each": ["i in item"],
                "where": ["i != i"],
                "coefficient": 1,
                "variable": "pair[i,i]",
            },
        ],
        cardinality_constraint_templates=[
            {
                "id": "one_pair",
                "type": "hard",
                "variables": [
                    {
                        "for_each": ["i in item", "j in item"],
                        "where": ["i < j"],
                        "variable": "pair[i,j]",
                    }
                ],
                "operator": "<=",
                "rhs": 1,
            }
        ],
    )


PROBLEMS: dict[str, Callable[[], OptimizationProblem]] = _merge(
    {"example_tsp_template": example_tsp_template},
    {
        "fixture_assignment_template": fixture_assignment_template,
        "fixture_shift_template": fixture_shift_template,
        "fixture_window_template": fixture_window_template,
        "fixture_mixed_template": fixture_mixed_template,
    },
    {
        "ring_window_terms_merged": ring_window_terms_merged,
        "parameter_rhs_and_weight": parameter_rhs_and_weight,
        "integer_family": integer_family,
        "soft_templates": soft_templates,
        "unused_family_variables": unused_family_variables,
    },
)

# Optima worked out by hand (or stated by the problem's description);
# recording refuses a golden whose exact solve disagrees. The three not
# stated above: parameter_rhs_and_weight takes t1 and t2 on mon and t3 on
# tue (3 + 1, every task done); integer_family makes two units of p1 and
# one of p2 (8 + 2.5 - 1 - 2, five hours); unused_family_variables takes
# the pair (a, c).
KNOWN_OPTIMA: dict[str, float] = {
    "example_tsp_template": 8.0,
    "fixture_assignment_template": 8.0,
    "fixture_shift_template": 7.0,
    "fixture_window_template": 12.0,
    "ring_window_terms_merged": 5.5,
    "parameter_rhs_and_weight": 4.0,
    "integer_family": 7.5,
    "unused_family_variables": 3.0,
}


# --------------------------------------------------------------------------
# Sections. Each takes the *template* problem and expands it itself.
# --------------------------------------------------------------------------


def _expand(problem: OptimizationProblem) -> ExpandedProblem:
    expansion = expand_problem(problem)
    if expansion.errors or expansion.problem is None:
        raise ValueError(f"{problem.name}: expansion failed: {_triples(expansion.errors)}")
    return expansion


def _triples(entries) -> list[list[str | None]]:
    return [[entry.code, entry.path, entry.message] for entry in entries]


def section_expanded(problem: OptimizationProblem) -> dict:
    return _expand(problem).problem.model_dump()


def section_expansion_warnings(problem: OptimizationProblem) -> list:
    return _triples(_expand(problem).warnings)


def section_snapshot(problem: OptimizationProblem) -> dict:
    expansion = _expand(problem)
    snapshot = snapshot_problem(expansion.problem)
    # The same two validations, taken on the expansion so the paths are
    # mapped back to the templates (spec §14.11).
    snapshot["validate_full_exact"] = validate_expanded(
        expansion, capabilities=_exact_capabilities()
    ).model_dump(mode="json")
    snapshot["validate_full_cqm_path"] = validate_expanded(
        expansion, model_type="cqm"
    ).model_dump(mode="json")
    return snapshot


def section_exact_solve(problem: OptimizationProblem) -> dict | None:
    """``record_compat_golden.section_exact_solve`` for a template problem.

    The size gate and the infeasibility diagnostics read the expanded
    problem; the solve itself gets the template problem, so the service's
    own expansion is part of what is frozen.
    """
    expanded = _expand(problem).problem
    penalty = ScaledPenaltyStrategy().initial_penalty(expanded)
    if BQMCompiler().compile(expanded, penalty).num_variables > EXACT_MAX_BQM_VARIABLES:
        return None
    on_exact = problem.model_copy(
        update={"solver": problem.solver.model_copy(update={"backend": "exact"})}
    )
    service = OptimizationService(registry=_local_registry(), policy=ExecutionPolicy())
    result = service.solve(on_exact)
    return {
        "status": result.status,
        "backend": result.backend,
        "objective_direction": result.objective_direction,
        "infeasibility_proven": result.infeasibility_proven,
        "optimality_proven": result.optimality_proven,
        "errors": _code_path(result.errors),
        "warnings": _code_path(result.warnings),
        "metadata": (
            None if result.metadata is None else _pick(result.metadata, _METADATA_FIELDS)
        ),
        "attempts": [_pick(attempt, _ATTEMPT_FIELDS) for attempt in result.attempts],
        "solutions": [
            {
                **_pick(solution, _SOLUTION_FIELDS),
                "constraint_evaluations": [
                    _pick(evaluation, _EVALUATION_FIELDS)
                    for evaluation in solution.constraint_evaluations
                ],
            }
            for solution in result.solutions
        ],
        "infeasibility": (
            None
            if result.infeasibility is None
            else _infeasibility(expanded, result.infeasibility)
        ),
    }


SECTIONS: dict[str, Callable[[OptimizationProblem], Any]] = {
    "expanded": section_expanded,
    "expansion_warnings": section_expansion_warnings,
    "snapshot": section_snapshot,
    "exact_solve": section_exact_solve,
}


# --------------------------------------------------------------------------
# Documents the expansion refuses
# --------------------------------------------------------------------------


def _error_base() -> dict:
    """A small valid ``1.3`` document every refused one starts from.

    U = 3 (the family) + 3 (the objective template) + 1 x (1 + 3) (the
    cardinality template) = 10; W = 3 + 3 + 1 + (1 + 2 + 3) = 13.
    """
    return {
        "version": VERSION,
        "name": "expansion error base",
        "index_sets": [{"name": "item", "elements": ["a", "b", "c"]}],
        "parameters": [
            {"name": "value", "indices": ["item"], "values": _rows(1, {"a": 3, "b": 1, "c": 2})}
        ],
        "variable_families": [{"name": "x", "indices": ["item"]}],
        "variables": [],
        "objective": {
            "direction": "maximize",
            "linear_terms": [],
            "linear_term_templates": [
                {"for_each": ["i in item"], "coefficient": "value[i]", "variable": "x[i]"}
            ],
        },
        "constraints": [],
        "cardinality_constraint_templates": [
            {
                "id": "at_most_two",
                "type": "hard",
                "variables": [{"for_each": ["i in item"], "variable": "x[i]"}],
                "operator": "<=",
                "rhs": 2,
            }
        ],
    }


def _edit(change: Callable[[dict], None]) -> Callable[[], dict]:
    def build() -> dict:
        document = _error_base()
        change(document)
        return document

    return build


def _set(path: tuple, value: Any) -> Callable[[dict], None]:
    def change(document: dict) -> None:
        target = document
        for key in path[:-1]:
            target = target[key]
        target[path[-1]] = value

    return change


def _unchanged(document: dict) -> None:
    pass


def _non_integer_cardinality_rhs(document: dict) -> None:
    # A parameter used as a cardinality rhs whose default is not a count.
    document["parameters"].append(
        {"name": "bound", "indices": ["item"], "default": 1.5, "values": []}
    )
    document["cardinality_constraint_templates"][0].update(
        {"for_each": ["k in item"], "rhs": "bound[k]"}
    )


def _version_omitted_with_integers(document: dict) -> None:
    del document["version"]
    document["variable_families"].append(
        {"name": "n", "indices": ["item"], "type": "integer", "lower_bound": 0, "upper_bound": 2}
    )
    document["cardinality_constraints"] = [
        {"id": "explicit_count", "type": "hard", "variables": ["x[a]", "x[b]"],
         "operator": "<=", "rhs": 1}
    ]


def _second_template_with_the_same_id(document: dict) -> None:
    document["cardinality_constraint_templates"].append(
        copy.deepcopy(document["cardinality_constraint_templates"][0])
    )


def _family_named_like_an_explicit_variable(document: dict) -> None:
    document["variables"] = [{"name": "x"}]


def _drop_value_row(document: dict) -> None:
    del document["parameters"][0]["values"][1]  # the row for "b"


def _many_static_errors(document: dict) -> None:
    # 26 member errors from one template, alternating an unknown explicit
    # variable and a syntax error: 20 are listed, the other 6 are counted
    # per code (UNKNOWN_VARIABLE first, as term 20 comes first).
    document["constraint_templates"] = [
        {
            "id": "many_terms",
            "type": "hard",
            "terms": [
                {"coefficient": 1, "variable": f"ghost_{k}" if k % 2 == 0 else "x[i"}
                for k in range(26)
            ],
            "operator": "<=",
            "rhs": 1,
        }
    ]


def _many_missing_values(document: dict) -> None:
    # 25 bindings each look up a different missing key of a parameter with
    # no rows and no default: 20 are listed, 5 are counted.
    elements = [f"e{k:02d}" for k in range(25)]
    document["index_sets"] = [{"name": "item", "elements": elements}]
    document["parameters"] = [{"name": "value", "indices": ["item"], "values": []}]


# name -> (document builder, max_template_bindings for the expansion)
ERROR_DOCUMENTS: dict[str, tuple[Callable[[], dict], int]] = {
    # TEMPLATE_REFERENCE_INVALID: an index count, a syntax error, an index
    # bound but never used, and a number written as a string.
    "reference_wrong_index_count": (
        _edit(_set(("objective", "linear_term_templates", 0, "variable"), "x[i,i]")),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    "reference_syntax_error": (
        _edit(_set(("objective", "linear_term_templates", 0, "coefficient"), "value[i")),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    "reference_index_never_used": (
        _edit(_set(("cardinality_constraint_templates", 0, "for_each"), ["j in item"])),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    "reference_number_as_string": (
        _edit(_set(("objective", "linear_term_templates", 0, "coefficient"), "2")),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    # INDEX_SET_INVALID
    "index_set_duplicate_element": (
        _edit(_set(("index_sets", 0, "elements"), ["a", "b", "a", "c"])),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    "index_set_mixed_types": (
        _edit(_set(("index_sets", 0, "elements"), ["a", "b", "c", 4])),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    # PARAMETER_TABLE_INVALID
    "parameter_key_not_in_set": (
        _edit(_set(("parameters", 0, "values", 2, "key"), ["z"])),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    "parameter_non_integer_cardinality_rhs": (
        _edit(_non_integer_cardinality_rhs),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    # PARAMETER_VALUE_MISSING
    "parameter_value_missing": (_edit(_drop_value_row), DEFAULT_MAX_TEMPLATE_BINDINGS),
    # DUPLICATE_TEMPLATE_NAME
    "duplicate_template_id": (
        _edit(_second_template_with_the_same_id),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    "family_named_like_an_explicit_variable": (
        _edit(_family_named_like_an_explicit_variable),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    # TEMPLATE_EXPANSION_LIMIT: U = 10 > 5 is refused before generating;
    # U = 10 <= 10 passes but W = 13 > 10 stops the generation.
    "limit_upper_bound": (_edit(_unchanged), 5),
    "limit_work": (_edit(_unchanged), 10),
    # FEATURE_REQUIRES_NEWER_VERSION: the template gate, with the notes for
    # an omitted version, cardinality constraints and integer families.
    "version_1_2_with_templates": (
        _edit(_set(("version",), "1.2")),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    "version_omitted_with_integers_and_cardinality": (
        _edit(_version_omitted_with_integers),
        DEFAULT_MAX_TEMPLATE_BINDINGS,
    ),
    # More than 20 errors from one source: the truncation suffix, once for
    # static errors of two codes and once for errors found while generating.
    "truncated_static_errors": (_edit(_many_static_errors), DEFAULT_MAX_TEMPLATE_BINDINGS),
    "truncated_missing_values": (_edit(_many_missing_values), DEFAULT_MAX_TEMPLATE_BINDINGS),
}


def expansion_errors(document: dict, max_template_bindings: int) -> dict:
    """What ``expand_problem`` reports for ``document``."""
    problem = OptimizationProblem.model_validate(document)
    expansion = expand_problem(problem, max_template_bindings=max_template_bindings)
    return {
        "max_template_bindings": max_template_bindings,
        "limit_exceeded": expansion.limit_exceeded,
        "errors": _triples(expansion.errors),
    }


# --------------------------------------------------------------------------
# Recording
# --------------------------------------------------------------------------


def _refuse_suspicious(name: str, problem: OptimizationProblem, entry: dict) -> None:
    """Raise rather than freeze an output that looks wrong (see the docstring)."""
    expanded = _expand(problem).problem
    penalty = ScaledPenaltyStrategy().initial_penalty(expanded)
    compiled = BQMCompiler().compile(expanded, penalty).num_variables
    estimated = estimate_compiled_variables(expanded)
    if estimated != compiled:
        raise ValueError(f"{name}: estimated {estimated} != compiled {compiled}")
    if name in KNOWN_OPTIMA:
        solve = entry["exact_solve"]
        if solve is None or solve["status"] != "success":
            raise ValueError(f"{name}: no exact optimum to compare")
        best = solve["solutions"][0]["objective_value"]
        if best != KNOWN_OPTIMA[name]:
            raise ValueError(f"{name}: optimum {best}, expected {KNOWN_OPTIMA[name]}")


def record_problem_1_3(name: str, problem: OptimizationProblem) -> dict:
    if problem.version != VERSION:
        raise ValueError(f"{name}: version {problem.version!r}, expected {VERSION!r}")
    entry: dict[str, Any] = {"version": problem.version}
    for section, snapshot in SECTIONS.items():
        entry[section] = snapshot(problem)
    _refuse_suspicious(name, problem, entry)
    return entry


def record() -> dict:
    if expand_problem(OptimizationProblem.model_validate(_error_base())).errors:
        raise ValueError("the error-document base does not expand")
    refused: dict[str, dict] = {}
    for name, (build, ceiling) in ERROR_DOCUMENTS.items():
        recorded = expansion_errors(build(), ceiling)
        if not recorded["errors"]:
            raise ValueError(f"error document {name!r} expanded without error")
        refused[name] = recorded
    return {
        "recorded_from": RECORDED_FROM,
        "problems": {
            name: record_problem_1_3(name, build()) for name, build in PROBLEMS.items()
        },
        "expansion_errors": refused,
    }


def main() -> None:
    GOLDEN_PATH.write_text(
        json.dumps(record(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        f"recorded {len(PROBLEMS)} problems and {len(ERROR_DOCUMENTS)} error "
        f"documents to {GOLDEN_PATH}"
    )


if __name__ == "__main__":
    main()
