"""Validator output on an expanded problem points back into the templates.

Schema 1.3 spec 2026-09-25 §14 (v4):

* §14.11 path mapping -- every row of the table: an issue the ordinary
  validator reports on a generated entry has its path rewritten to the
  template (``variables[k]`` -> ``variable_families[f]``, a constraint term
  ``terms[j]`` -> the term template ``terms[m]`` that generated it, ...) and
  ``(generated by <template path>)`` appended, with the outer binding
  (``with i=a``) for a generated constraint; other paths are unchanged.
* §14.11 bounded collector -- at most twenty errors per template, the rest
  counted per code on the last one listed; generated warnings aggregated per
  (code, mapped path) with the number of entries that got them.
* §14.11 special cases -- DUPLICATE_TERM_MERGED attributed to the template
  of the first generated repeat (explicit-only duplicates keep their path,
  several duplicates of one template aggregate); a cross-list
  DUPLICATE_CONSTRAINT_ID stays on the explicit entry with a note naming
  the template; UNKNOWN_VARIABLE on ``x[a, 0]`` gets the no-spaces hint;
  NO_VARIABLES says when every generated variable was left out.
* §14.8 -- with any error every warning, the expansion's own included, is
  dropped; errors and warnings of explicit entries are exactly what the
  same problem without templates gets; expansion warnings come first.
"""

import copy
import re

import pytest

from annealbridge.models import OptimizationProblem
from annealbridge.validation import (
    expand_problem,
    validate_expanded,
    validate_problem,
    validate_problem_full,
)

ITEM = {"name": "item", "elements": ["a", "b", "c"]}


def document(**extra) -> dict:
    """A 1.3 document with family x[item] and one linear term per x[i].

    ``objective`` in ``extra`` is merged into the objective; every other key
    replaces the top-level field.
    """
    data = {
        "version": "1.3",
        "name": "attribution",
        "index_sets": [ITEM],
        "variable_families": [{"name": "x", "indices": ["item"]}],
        "variables": [],
        "objective": {
            "direction": "minimize",
            "linear_terms": [],
            "linear_term_templates": [
                {"for_each": ["i in item"], "coefficient": 1, "variable": "x[i]"}
            ],
        },
        "constraints": [],
    }
    for key, value in extra.items():
        if key == "objective":
            data["objective"].update(value)
        else:
            data[key] = value
    return data


def problem(**extra) -> OptimizationProblem:
    return OptimizationProblem.model_validate(document(**extra))


def errors_of(candidate: OptimizationProblem) -> list[tuple[str, str | None, str]]:
    result = validate_problem_full(candidate)
    assert not result.valid
    assert result.warnings == []
    # The errors-only entry point reports exactly the same errors.
    assert validate_problem(candidate) == result.errors
    return [(error.code, error.path, error.message) for error in result.errors]


def warnings_of(candidate: OptimizationProblem) -> list[tuple[str, str | None, str]]:
    result = validate_problem_full(candidate)
    assert result.valid, result.errors
    return [(warning.code, warning.path, warning.message) for warning in result.warnings]


# --------------------------------------------------------------------------
# §14.11 path mapping, one row at a time
# --------------------------------------------------------------------------


def test_variables_row_maps_to_the_family():
    # Explicit x[b] first; the second family generates x[b] again at
    # variables[5], after y[a..c] and x[a].
    candidate = problem(
        variables=[{"name": "x[b]"}],
        variable_families=[
            {"name": "y", "indices": ["item"]},
            {"name": "x", "indices": ["item"]},
        ],
        objective={
            "linear_term_templates": [
                {"for_each": ["i in item"], "coefficient": 1, "variable": "x[i]"},
                {"for_each": ["i in item"], "coefficient": 1, "variable": "y[i]"},
            ]
        },
    )
    expansion = expand_problem(candidate)
    assert [v.name for v in expansion.problem.variables] == [
        "x[b]", "y[a]", "y[b]", "y[c]", "x[a]", "x[b]", "x[c]",
    ]  # fmt: skip
    assert errors_of(candidate) == [
        (
            "DUPLICATE_VARIABLE",
            "variable_families[1]",
            "Variable x[b] is declared more than once "
            "(generated by variable_families[1])",
        )
    ]


def test_quadratic_terms_row_maps_to_the_term_template():
    # One explicit term first, then i x j without "i != j": the diagonal
    # x[i]*x[i] is reported by the ordinary validator, entry by entry.
    candidate = problem(
        objective={
            "quadratic_terms": [{"variable1": "x[a]", "variable2": "x[b]", "coefficient": 1}],
            "quadratic_term_templates": [
                {
                    "for_each": ["i in item", "j in item"],
                    "coefficient": 1,
                    "variable1": "x[i]",
                    "variable2": "x[j]",
                }
            ],
        }
    )
    assert errors_of(candidate) == [
        (
            "SELF_QUADRATIC_TERM",
            "objective.quadratic_term_templates[0]",
            f"Quadratic term references x[{name}] twice; for binary variables "
            "x*x = x, use a linear term instead "
            "(generated by objective.quadratic_term_templates[0])",
        )
        for name in "abc"
    ]


def test_constraint_row_maps_with_its_binding():
    # lower[i] sums the x[j] before i: lower[a] has no term at all. The
    # outer index i is only used in the member's where (spec §14.5).
    candidate = problem(
        constraint_templates=[
            {
                "id": "lower",
                "type": "hard",
                "for_each": ["i in item"],
                "terms": [
                    {
                        "for_each": ["j in item"],
                        "where": ["j < i"],
                        "coefficient": 1,
                        "variable": "x[j]",
                    }
                ],
                "operator": "<=",
                "rhs": 1,
            }
        ]
    )
    assert errors_of(candidate) == [
        (
            "EMPTY_CONSTRAINT",
            "constraint_templates[0]",
            "Constraint lower[a] has no terms (generated by constraint_templates[0] with i=a)",
        )
    ]


def test_constraint_term_row_maps_to_the_generating_term_template():
    # cap[i] = x[a] + x[b] + x[c] + frac[i] * x[i] <= 5: frac[a] = 0.5 puts a
    # non-integer coefficient at terms[3], generated by term template 1.
    candidate = problem(
        parameters=[
            {"name": "frac", "indices": ["item"], "default": 1,
             "values": [{"key": ["a"], "value": 0.5}]}
        ],
        constraints=[
            {"id": "explicit_first", "type": "hard",
             "terms": [{"variable": "x[a]", "coefficient": 1}], "operator": "<=", "rhs": 1}
        ],
        constraint_templates=[
            {
                "id": "cap",
                "type": "hard",
                "for_each": ["i in item"],
                "terms": [
                    {"for_each": ["j in item"], "coefficient": 1, "variable": "x[j]"},
                    {"coefficient": "frac[i]", "variable": "x[i]"},
                ],
                "operator": "<=",
                "rhs": 5,
            }
        ],
    )  # fmt: skip
    expansion = expand_problem(candidate)
    assert expansion.problem.constraints[1].terms[3].coefficient == 0.5
    assert errors_of(candidate) == [
        (
            "NON_INTEGER_INEQUALITY",
            "constraint_templates[0].terms[1]",
            "Inequality constraint cap[a] requires integer coefficients and rhs for "
            "slack encoding, got 0.5 (generated by constraint_templates[0] with i=a)",
        )
    ]


def test_constraint_rhs_and_weight_rows_map_to_the_template_fields():
    candidate = problem(
        parameters=[
            {"name": "half", "indices": ["item"], "default": 1,
             "values": [{"key": ["a"], "value": 0.5}]},
            {"name": "w", "indices": ["item"], "default": 2,
             "values": [{"key": ["b"], "value": -1}]},
        ],
        constraint_templates=[
            {
                "id": "soft_cap",
                "type": "soft",
                "for_each": ["i in item"],
                "terms": [{"coefficient": 1, "variable": "x[i]"}],
                "operator": "<=",
                "rhs": "half[i]",
                "weight": "w[i]",
            }
        ],
    )  # fmt: skip
    assert errors_of(candidate) == [
        (
            "NON_INTEGER_INEQUALITY",
            "constraint_templates[0].rhs",
            "Inequality constraint soft_cap[a] requires integer coefficients and rhs "
            "for slack encoding, got 0.5 (generated by constraint_templates[0] with i=a)",
        ),
        (
            "SOFT_CONSTRAINT_MISSING_WEIGHT",
            "constraint_templates[0].weight",
            "Soft constraint soft_cap[b] requires a weight > 0, got -1.0 "
            "(generated by constraint_templates[0] with i=b)",
        ),
    ]


def test_cardinality_row_maps_with_a_two_index_binding():
    candidate = problem(
        cardinality_constraint_templates=[
            {
                "id": "pair",
                "type": "hard",
                "for_each": ["i in item", "j in item"],
                "where": ["i < j"],
                "variables": ["x[i]", "x[j]"],
                "operator": "==",
                "rhs": 3,
            }
        ]
    )
    assert errors_of(candidate) == [
        (
            "TRIVIALLY_INFEASIBLE",
            "cardinality_constraint_templates[0]",
            f"Hard cardinality constraint pair[{i},{j}] counts 2 variables, so "
            "between 0 and 2 are chosen, but requires == 3 "
            f"(generated by cardinality_constraint_templates[0] with i={i}, j={j})",
        )
        for i, j in (("a", "b"), ("a", "c"), ("b", "c"))
    ]


def test_cardinality_member_row_maps_to_the_generating_member_template():
    # all_plus[i] counts x[a], x[b], x[c] (member 0) and then x[i] again
    # (member 1): the repeat sits at variables[3], generated by member 1.
    candidate = problem(
        cardinality_constraints=[
            {"id": "explicit_first", "type": "hard", "variables": ["x[a]", "x[b]"],
             "operator": "<=", "rhs": 1}
        ],
        cardinality_constraint_templates=[
            {
                "id": "all_plus",
                "type": "hard",
                "for_each": ["i in item"],
                "variables": [{"for_each": ["j in item"], "variable": "x[j]"}, "x[i]"],
                "operator": ">=",
                "rhs": 1,
            }
        ],
    )  # fmt: skip
    assert errors_of(candidate) == [
        (
            "DUPLICATE_CARDINALITY_VARIABLE",
            "cardinality_constraint_templates[0].variables[1]",
            f"Cardinality constraint all_plus[{name}] lists variable 'x[{name}]' more "
            "than once; each variable is counted once "
            f"(generated by cardinality_constraint_templates[0] with i={name})",
        )
        for name in "abc"
    ]


def test_cardinality_weight_row_maps_to_the_template_weight():
    candidate = problem(
        parameters=[
            {"name": "w", "indices": ["item"], "default": 2,
             "values": [{"key": ["b"], "value": 0}]}
        ],
        cardinality_constraint_templates=[
            {
                "id": "one",
                "type": "soft",
                "for_each": ["i in item"],
                "variables": ["x[i]"],
                "operator": "==",
                "rhs": 1,
                "weight": "w[i]",
            }
        ],
    )  # fmt: skip
    assert errors_of(candidate) == [
        (
            "SOFT_CONSTRAINT_MISSING_WEIGHT",
            "cardinality_constraint_templates[0].weight",
            "Soft constraint one[b] requires a weight > 0, got 0.0 "
            "(generated by cardinality_constraint_templates[0] with i=b)",
        )
    ]


def test_other_paths_are_unchanged():
    # An explicit entry, a solver field and a whole list keep their paths
    # and messages even when the document has templates.
    candidate = problem(
        solver={"num_reads": 0},
        constraints=[
            {"id": "bad", "type": "hard", "terms": [{"variable": "zz", "coefficient": 1}],
             "operator": "<=", "rhs": 1}
        ],
    )  # fmt: skip
    assert errors_of(candidate) == [
        ("UNKNOWN_VARIABLE", "constraints[0].terms[0]", "Variable zz does not exist"),
        (
            "INVALID_SOLVER_PREFERENCE",
            "solver.num_reads",
            "solver.num_reads must be > 0, got 0",
        ),
    ]


def locate_problem() -> OptimizationProblem:
    """Explicit entries plus two templates in every list, for ``locate``."""
    return problem(
        variables=[{"name": "u"}],
        variable_families=[
            {"name": "x", "indices": ["item"]},
            {"name": "y", "indices": ["item"]},
        ],
        objective={
            "linear_terms": [{"variable": "u", "coefficient": 1}],
            "quadratic_terms": [{"variable1": "u", "variable2": "x[a]", "coefficient": 1}],
            "linear_term_templates": [
                {"for_each": ["i in item"], "coefficient": 1, "variable": "x[i]"},
                {"for_each": ["i in item"], "coefficient": 2, "variable": "y[i]"},
            ],
            "quadratic_term_templates": [
                {"for_each": ["i in item", "j in item"], "where": ["i < j"],
                 "coefficient": 1, "variable1": "x[i]", "variable2": "y[j]"},
                {"for_each": ["i in item"], "coefficient": 1,
                 "variable1": "x[i]", "variable2": "y[i]"},
            ],
        },
        constraints=[
            {"id": "explicit", "type": "hard",
             "terms": [{"variable": "u", "coefficient": 1}], "operator": "<=", "rhs": 1}
        ],
        constraint_templates=[
            {"id": "c0", "type": "hard", "terms": [{"coefficient": 1, "variable": "u"}],
             "operator": "<=", "rhs": 1},
            {"id": "c1", "type": "soft", "for_each": ["i in item"],
             "terms": [
                 {"for_each": ["j in item"], "coefficient": 1, "variable": "x[j]"},
                 {"coefficient": 1, "variable": "y[i]"},
             ],
             "operator": "<=", "rhs": 3, "weight": 1},
        ],
        cardinality_constraints=[
            {"id": "explicit_card", "type": "hard", "variables": ["u", "x[a]"],
             "operator": "<=", "rhs": 1}
        ],
        cardinality_constraint_templates=[
            {"id": "k0", "type": "soft", "for_each": ["i in item", "j in item"],
             "where": ["i < j"],
             "variables": [
                 {"for_each": ["m in item"], "where": ["m < j"], "variable": "y[m]"},
                 "x[i]",
             ],
             "operator": ">=", "rhs": 1, "weight": 2},
        ],
    )  # fmt: skip


# (expanded path, mapped path, source, binding) per §14.11 row. The
# expanded lists of locate_problem():
#   variables: u, x[a..c], y[a..c]
#   linear_terms: u, x[a..c] (template 0), y[a..c] (template 1)
#   quadratic_terms: explicit, 3 pairs i<j (template 0), 3 diagonals (template 1)
#   constraints: explicit, c0, c1[a], c1[b], c1[c]  (c1: 3 x-terms, then y[i])
#   cardinality: explicit_card, k0[a,b], k0[a,c], k0[b,c]; k0 lists the y[m]
#   with m < j (member 0: one for j=b, two for j=c), then x[i] (member 1)
LOCATE_ROWS = [
    ("variables[1]", "variable_families[0]", "variable_families[0]", ""),
    ("variables[6]", "variable_families[1]", "variable_families[1]", ""),
    (
        "objective.linear_terms[5].coefficient",
        "objective.linear_term_templates[1].coefficient",
        "objective.linear_term_templates[1]",
        "",
    ),
    (
        "objective.quadratic_terms[4]",
        "objective.quadratic_term_templates[1]",
        "objective.quadratic_term_templates[1]",
        "",
    ),
    ("constraints[1]", "constraint_templates[0]", "constraint_templates[0]", ""),
    ("constraints[3]", "constraint_templates[1]", "constraint_templates[1]", " with i=b"),
    (
        "constraints[3].terms[2].coefficient",
        "constraint_templates[1].terms[0].coefficient",
        "constraint_templates[1]",
        " with i=b",
    ),
    (
        "constraints[4].terms[3]",
        "constraint_templates[1].terms[1]",
        "constraint_templates[1]",
        " with i=c",
    ),
    ("constraints[2].rhs", "constraint_templates[1].rhs", "constraint_templates[1]", " with i=a"),
    (
        "constraints[2].weight",
        "constraint_templates[1].weight",
        "constraint_templates[1]",
        " with i=a",
    ),
    (
        "cardinality_constraints[2]",
        "cardinality_constraint_templates[0]",
        "cardinality_constraint_templates[0]",
        " with i=a, j=c",
    ),
    (
        "cardinality_constraints[3].variables[0]",
        "cardinality_constraint_templates[0].variables[0]",
        "cardinality_constraint_templates[0]",
        " with i=b, j=c",
    ),
    (
        "cardinality_constraints[3].variables[2]",
        "cardinality_constraint_templates[0].variables[1]",
        "cardinality_constraint_templates[0]",
        " with i=b, j=c",
    ),
    (
        "cardinality_constraints[1].variables[1]",
        "cardinality_constraint_templates[0].variables[1]",
        "cardinality_constraint_templates[0]",
        " with i=a, j=b",
    ),
    (
        "cardinality_constraints[1].weight",
        "cardinality_constraint_templates[0].weight",
        "cardinality_constraint_templates[0]",
        " with i=a, j=b",
    ),
]


@pytest.mark.parametrize(("path", "mapped", "source", "binding"), LOCATE_ROWS)
def test_locate_maps_every_row_of_the_table(path, mapped, source, binding):
    expansion = expand_problem(locate_problem())
    assert expansion.errors == ()
    location = expansion.locate(path)
    assert location is not None
    assert location.path == mapped
    assert location.source == source
    assert location.suffix == f" (generated by {source}{binding})"


@pytest.mark.parametrize(
    "path",
    [
        "variables[0]",
        "objective.linear_terms[0]",
        "objective.quadratic_terms[0]",
        "constraints[0]",
        "constraints[0].terms[0]",
        "cardinality_constraints[0].variables[1]",
        "variables",
        "objective.linear_terms",
        "version",
        "solver.num_reads",
        None,
    ],
)
def test_locate_leaves_explicit_and_whole_problem_paths_alone(path):
    assert expand_problem(locate_problem()).locate(path) is None


# --------------------------------------------------------------------------
# §14.11 bounded collection
# --------------------------------------------------------------------------


def many_errors_problem() -> OptimizationProblem:
    """many[k] for 25 k: each has a non-integer rhs and a negative weight.

    ``_check_constraint`` reports the rhs before the weight, so template 0
    yields NON_INTEGER_INEQUALITY, SOFT_CONSTRAINT_MISSING_WEIGHT, ... fifty
    errors in that alternating order; template 1 yields two more.
    """
    return OptimizationProblem.model_validate(
        {
            "version": "1.3",
            "name": "many errors",
            "index_sets": [
                {"name": "n", "elements": list(range(1, 26))},
                {"name": "item", "elements": ["a", "b"]},
            ],
            "parameters": [
                {"name": "half", "indices": ["n"], "default": 0.5},
                {"name": "neg", "indices": ["n"], "default": -1},
                {"name": "neg2", "indices": ["item"], "default": -1},
            ],
            "variable_families": [
                {"name": "y", "indices": ["n"]},
                {"name": "z", "indices": ["item"]},
            ],
            "variables": [{"name": "u"}],
            "objective": {
                "direction": "minimize",
                "linear_terms": [{"variable": "u", "coefficient": 1}],
                "linear_term_templates": [
                    {"for_each": ["k in n"], "coefficient": 1, "variable": "y[k]"},
                    {"for_each": ["i in item"], "coefficient": 1, "variable": "z[i]"},
                ],
            },
            "constraints": [
                {"id": "explicit_bad", "type": "soft",
                 "terms": [{"variable": "u", "coefficient": 1}], "operator": "<=", "rhs": 1}
            ],
            "constraint_templates": [
                {"id": "many", "type": "soft", "for_each": ["k in n"],
                 "terms": [{"coefficient": 1, "variable": "y[k]"}],
                 "operator": "<=", "rhs": "half[k]", "weight": "neg[k]"},
                {"id": "few", "type": "soft", "for_each": ["i in item"],
                 "terms": [{"coefficient": 1, "variable": "z[i]"}],
                 "operator": "==", "rhs": 1, "weight": "neg2[i]"},
            ],
        }
    )  # fmt: skip


def test_at_most_twenty_errors_per_template_and_the_rest_counted():
    errors = validate_problem_full(many_errors_problem()).errors
    # The explicit error, twenty from template 0, both from template 1.
    assert len(errors) == 1 + 20 + 2
    assert (errors[0].code, errors[0].path) == (
        "SOFT_CONSTRAINT_MISSING_WEIGHT",
        "constraints[0].weight",
    )
    assert "generated by" not in errors[0].message

    listed = errors[1:21]
    assert [error.code for error in listed] == [
        "NON_INTEGER_INEQUALITY",
        "SOFT_CONSTRAINT_MISSING_WEIGHT",
    ] * 10
    assert [error.path for error in listed] == [
        "constraint_templates[0].rhs",
        "constraint_templates[0].weight",
    ] * 10
    for position, error in enumerate(listed):
        k = position // 2 + 1
        assert f"many[{k}]" in error.message
        assert f"(generated by constraint_templates[0] with k={k})" in error.message
    # Only the twentieth carries the count of the thirty left out, per code
    # in first-seen order.
    for error in listed[:-1]:
        assert "not listed" not in error.message
    last = listed[-1].message
    assert last.startswith(
        "Soft constraint many[10] requires a weight > 0, got -1.0 "
        "(generated by constraint_templates[0] with k=10); 30 more errors from "
    )
    assert last.endswith(
        " are not listed (NON_INTEGER_INEQUALITY ×15, SOFT_CONSTRAINT_MISSING_WEIGHT ×15)"
    )

    # The cap is per template: template 1's errors are all listed.
    assert [(e.code, e.path) for e in errors[21:]] == [
        ("SOFT_CONSTRAINT_MISSING_WEIGHT", "constraint_templates[1].weight")
    ] * 2
    assert all("not listed" not in e.message for e in errors[21:])


def test_errors_only_entry_points_cap_alike():
    candidate = many_errors_problem()
    full = validate_problem_full(candidate).errors
    assert validate_problem(candidate) == full
    assert validate_expanded(expand_problem(candidate), errors_only=True).errors == full


def test_generated_warnings_are_aggregated_per_code_and_path():
    candidate = problem(
        parameters=[{"name": "tiny", "indices": ["item"], "default": 0.001}],
        variable_families=[
            {"name": "x", "indices": ["item"]},
            {"name": "unused", "indices": ["item"]},
        ],
        constraint_templates=[
            {"id": "loose", "type": "hard", "for_each": ["i in item"],
             "terms": [{"coefficient": 1, "variable": "x[i]"}], "operator": "<=", "rhs": 5},
            {"id": "weak", "type": "soft", "for_each": ["i in item"],
             "terms": [{"coefficient": 1, "variable": "x[i]"}],
             "operator": "==", "rhs": 1, "weight": "tiny[i]"},
        ],
    )  # fmt: skip
    assert warnings_of(candidate) == [
        # The expansion's own warnings come first (spec §14.8).
        (
            "UNUSED_TEMPLATE_VARIABLES",
            "variable_families[1]",
            "3 of the 3 variables of family unused appear in no objective term or "
            "constraint and were left out: unused[a], unused[b], unused[c]",
        ),
        (
            "SOFT_WEIGHT_SMALL",
            "constraint_templates[1].weight",
            "Soft constraint weak[a] has weight 0.001, below 0.01 of the objective "
            "scale 3.0; it will barely influence solutions "
            "(generated by constraint_templates[1] with i=a); "
            "3 generated entries from this template get this warning",
        ),
        (
            "REDUNDANT_CONSTRAINT",
            "constraint_templates[0]",
            "Inequality constraint loose[a] is always satisfied: lhs maximum 1.0 never "
            "exceeds the bound (generated by constraint_templates[0] with i=a); "
            "3 generated entries from this template get this warning",
        ),
    ]


def test_a_warning_on_a_single_generated_entry_has_no_count():
    # Without for_each the template generates one constraint named by its
    # id, and the suffix has no binding.
    candidate = problem(
        variables=[{"name": "u"}],
        objective={"linear_terms": [{"variable": "u", "coefficient": 1}]},
        constraint_templates=[
            {"id": "loose", "type": "hard",
             "terms": [{"coefficient": 1, "variable": "u"}], "operator": "<=", "rhs": 5}
        ],
    )  # fmt: skip
    assert warnings_of(candidate) == [
        (
            "REDUNDANT_CONSTRAINT",
            "constraint_templates[0]",
            "Inequality constraint loose is always satisfied: lhs maximum 1.0 never "
            "exceeds the bound (generated by constraint_templates[0])",
        )
    ]


# --------------------------------------------------------------------------
# §14.11 special cases
# --------------------------------------------------------------------------


def test_duplicate_term_merged_is_attributed_to_the_template():
    # x[a]: explicit, template 0, template 1 -> first repeat is template 0.
    # x[b], x[c]: template 0, template 1 -> both template 1, aggregated.
    # z: explicit twice -> original path and message.
    candidate = problem(
        variables=[{"name": "z"}],
        objective={
            "linear_terms": [
                {"variable": "x[a]", "coefficient": 1},
                {"variable": "z", "coefficient": 1},
                {"variable": "z", "coefficient": 2},
            ],
            "linear_term_templates": [
                {"for_each": ["i in item"], "coefficient": 1, "variable": "x[i]"},
                {"for_each": ["i in item"], "coefficient": 2, "variable": "x[i]"},
            ],
        },
    )
    assert warnings_of(candidate) == [
        (
            "DUPLICATE_TERM_MERGED",
            "objective.linear_term_templates[0]",
            "Variable x[a] appears 3 times in objective.linear_terms; coefficients "
            "will be summed by the compiler "
            "(generated by objective.linear_term_templates[0])",
        ),
        (
            "DUPLICATE_TERM_MERGED",
            "objective.linear_terms",
            "Variable z appears 2 times in objective.linear_terms; coefficients "
            "will be summed by the compiler",
        ),
        (
            "DUPLICATE_TERM_MERGED",
            "objective.linear_term_templates[1]",
            "Variable x[b] appears 2 times in objective.linear_terms; coefficients "
            "will be summed by the compiler "
            "(generated by objective.linear_term_templates[1]); "
            "2 generated entries from this template get this warning",
        ),
    ]


def test_duplicate_quadratic_pairs_are_attributed_to_the_template():
    # i x j with i != j generates both (x[a],x[b]) and (x[b],x[a]).
    candidate = problem(
        objective={
            "quadratic_term_templates": [
                {"for_each": ["i in item", "j in item"], "where": ["i != j"],
                 "coefficient": 1, "variable1": "x[i]", "variable2": "x[j]"}
            ]
        }
    )  # fmt: skip
    [(code, path, message)] = warnings_of(candidate)
    assert (code, path) == ("DUPLICATE_TERM_MERGED", "objective.quadratic_term_templates[0]")
    assert message.endswith(
        "appears 2 times in objective.quadratic_terms; coefficients will be summed "
        "by the compiler (generated by objective.quadratic_term_templates[0]); "
        "3 generated entries from this template get this warning"
    )


def test_duplicate_term_merged_of_explicit_terms_is_unchanged_by_templates():
    with_templates = problem(
        variables=[{"name": "z"}],
        objective={
            "linear_terms": [
                {"variable": "z", "coefficient": 1},
                {"variable": "z", "coefficient": 2},
            ]
        },
    )
    without = OptimizationProblem.model_validate(
        {
            "version": "1.3",
            "name": "attribution",
            "variables": [{"name": "z"}],
            "objective": {
                "direction": "minimize",
                "linear_terms": [
                    {"variable": "z", "coefficient": 1},
                    {"variable": "z", "coefficient": 2},
                ],
            },
            "constraints": [],
        }
    )
    assert warnings_of(with_templates) == warnings_of(without)


def test_cross_list_duplicate_id_stays_on_the_explicit_entry_with_a_note():
    # The linear template generates cap[b]; the explicit cardinality
    # constraint cap[b] comes later in the id check, so it gets the error.
    candidate = problem(
        constraint_templates=[
            {"id": "cap", "type": "hard", "for_each": ["i in item"],
             "terms": [{"coefficient": 1, "variable": "x[i]"}], "operator": "<=", "rhs": 1}
        ],
        cardinality_constraints=[
            {"id": "cap[b]", "type": "hard", "variables": ["x[a]", "x[b]"],
             "operator": "==", "rhs": 1}
        ],
    )  # fmt: skip
    assert errors_of(candidate) == [
        (
            "DUPLICATE_CONSTRAINT_ID",
            "cardinality_constraints[0]",
            "Constraint id cap[b] is used more than once "
            "(the same id is generated by constraint_templates[0] with i=b)",
        )
    ]


def test_same_list_duplicate_id_maps_to_the_template():
    candidate = problem(
        constraints=[
            {"id": "cap[b]", "type": "hard",
             "terms": [{"variable": "x[a]", "coefficient": 1}], "operator": "<=", "rhs": 1}
        ],
        constraint_templates=[
            {"id": "cap", "type": "hard", "for_each": ["i in item"],
             "terms": [{"coefficient": 1, "variable": "x[i]"}], "operator": "<=", "rhs": 1}
        ],
    )  # fmt: skip
    assert errors_of(candidate) == [
        (
            "DUPLICATE_CONSTRAINT_ID",
            "constraint_templates[0]",
            "Constraint id cap[b] is used more than once "
            "(generated by constraint_templates[0] with i=b)",
        )
    ]


def test_unknown_variable_with_spaces_gets_the_generated_name_hint():
    candidate = problem(
        index_sets=[ITEM, {"name": "pos", "elements": [0, 1]}],
        variable_families=[{"name": "x", "indices": ["item", "pos"]}],
        objective={
            "linear_terms": [
                {"variable": "x[a, 0]", "coefficient": 1},
                {"variable": "zz", "coefficient": 1},
            ],
            "linear_term_templates": [
                {"for_each": ["i in item", "p in pos"], "coefficient": 1, "variable": "x[i,p]"}
            ],
        },
    )
    [(code, path, message), unrelated] = errors_of(candidate)
    assert (code, path) == ("UNKNOWN_VARIABLE", "objective.linear_terms[0]")
    assert message.startswith("Variable x[a, 0] does not exist (")
    # Spec §14.11: the hint says generated names are family[e1,e2] exactly,
    # without spaces.
    assert "family[e1,e2], without spaces" in message
    # A name that is not a family name plus "[" gets no hint.
    assert unrelated == ("UNKNOWN_VARIABLE", "objective.linear_terms[1]", "Variable zz does not exist")


def test_no_variables_says_every_generated_variable_was_left_out():
    candidate = problem(objective={"linear_term_templates": []})
    expansion = expand_problem(candidate)
    assert [w.code for w in expansion.warnings] == ["UNUSED_TEMPLATE_VARIABLES"]
    assert errors_of(candidate) == [
        (
            "NO_VARIABLES",
            "variables",
            "Problem declares no variables; there is nothing to optimize "
            "(variable_families generated 3 variables, but no objective term or "
            "constraint uses any of them, so all were left out)",
        )
    ]


# --------------------------------------------------------------------------
# Errors drop every warning; explicit entries are unaffected
# --------------------------------------------------------------------------


def test_any_error_drops_every_warning_including_the_expansions():
    candidate = problem(
        variable_families=[
            {"name": "x", "indices": ["item"]},
            {"name": "unused", "indices": ["item"]},
        ],
        constraint_templates=[
            {"id": "loose", "type": "hard", "for_each": ["i in item"],
             "terms": [{"coefficient": 1, "variable": "x[i]"}], "operator": "<=", "rhs": 5}
        ],
        constraints=[
            {"id": "bad", "type": "hard", "terms": [{"variable": "zz", "coefficient": 1}],
             "operator": "<=", "rhs": 1}
        ],
    )  # fmt: skip
    expansion = expand_problem(candidate)
    assert [w.code for w in expansion.warnings] == ["UNUSED_TEMPLATE_VARIABLES"]
    result = validate_expanded(expansion)
    assert not result.valid
    assert [e.code for e in result.errors] == ["UNKNOWN_VARIABLE"]
    assert result.warnings == []
    assert validate_problem_full(candidate).warnings == []


EXPLICIT_WITH_ERRORS = {
    "variables": [{"name": "u"}, {"name": "v"}],
    "linear_terms": [
        {"variable": "u", "coefficient": 1},
        {"variable": "v", "coefficient": 1},
    ],
    "constraints": [
        {"id": "unknown", "type": "hard", "terms": [{"variable": "zz", "coefficient": 1}],
         "operator": "<=", "rhs": 1},
        {"id": "no_weight", "type": "soft", "terms": [{"variable": "u", "coefficient": 1}],
         "operator": "==", "rhs": 1},
        {"id": "dup", "type": "hard", "terms": [{"variable": "u", "coefficient": 0.5}],
         "operator": ">=", "rhs": 0},
    ],
    "cardinality_constraints": [
        {"id": "dup", "type": "hard", "variables": ["u", "u"], "operator": "==", "rhs": 3}
    ],
}  # fmt: skip

EXPLICIT_WITH_WARNINGS = {
    "variables": [{"name": "u"}, {"name": "v"}],
    "linear_terms": [
        {"variable": "u", "coefficient": 1},
        {"variable": "v", "coefficient": 1},
        {"variable": "u", "coefficient": 1},
    ],
    "constraints": [
        {"id": "redundant", "type": "hard",
         "terms": [{"variable": "u", "coefficient": 1}, {"variable": "v", "coefficient": 1}],
         "operator": "<=", "rhs": 5},
        {"id": "amo", "type": "hard",
         "terms": [{"variable": "u", "coefficient": 1}, {"variable": "v", "coefficient": 1}],
         "operator": "<=", "rhs": 1},
        {"id": "never", "type": "soft",
         "terms": [{"variable": "u", "coefficient": 1}, {"variable": "v", "coefficient": 1}],
         "operator": ">=", "rhs": 3, "weight": 100},
    ],
    "cardinality_constraints": [
        {"id": "loose_card", "type": "hard", "variables": ["u", "v"], "operator": "<=",
         "rhs": 2}
    ],
}  # fmt: skip


def explicit_problem(explicit: dict, *, templates: bool) -> OptimizationProblem:
    """``explicit`` alone, or with warning-free templates added after it."""
    data = {
        "version": "1.3",
        "name": "explicit entries",
        "variables": copy.deepcopy(explicit["variables"]),
        "objective": {
            "direction": "minimize",
            "linear_terms": copy.deepcopy(explicit["linear_terms"]),
        },
        "constraints": copy.deepcopy(explicit["constraints"]),
        "cardinality_constraints": copy.deepcopy(explicit["cardinality_constraints"]),
    }
    if templates:
        data["index_sets"] = [ITEM]
        data["variable_families"] = [{"name": "x", "indices": ["item"]}]
        data["objective"]["linear_term_templates"] = [
            {"for_each": ["i in item"], "coefficient": 1, "variable": "x[i]"}
        ]
        data["constraint_templates"] = [
            {"id": "pair_with_u", "type": "hard", "for_each": ["i in item"],
             "terms": [{"coefficient": 1, "variable": "x[i]"},
                       {"coefficient": 1, "variable": "u"}],
             "operator": ">=", "rhs": 1}
        ]  # fmt: skip
        data["cardinality_constraint_templates"] = [
            {"id": "one_x", "type": "hard",
             "variables": [{"for_each": ["i in item"], "variable": "x[i]"}],
             "operator": "==", "rhs": 1}
        ]  # fmt: skip
    return OptimizationProblem.model_validate(data)


def test_explicit_errors_are_the_same_with_and_without_templates():
    with_templates = explicit_problem(EXPLICIT_WITH_ERRORS, templates=True)
    without = explicit_problem(EXPLICIT_WITH_ERRORS, templates=False)
    assert with_templates.has_templates() and not without.has_templates()
    ours = validate_problem_full(with_templates)
    theirs = validate_problem_full(without)
    assert not theirs.valid
    assert {e.code for e in theirs.errors} >= {
        "UNKNOWN_VARIABLE",
        "SOFT_CONSTRAINT_MISSING_WEIGHT",
        "NON_INTEGER_INEQUALITY",
        "DUPLICATE_CONSTRAINT_ID",
        "DUPLICATE_CARDINALITY_VARIABLE",
    }
    assert ours.errors == theirs.errors
    assert validate_problem(with_templates) == validate_problem(without)


def test_explicit_warnings_are_the_same_with_and_without_templates():
    with_templates = explicit_problem(EXPLICIT_WITH_WARNINGS, templates=True)
    without = explicit_problem(EXPLICIT_WITH_WARNINGS, templates=False)
    # The templates themselves are warning-free: no expansion warning.
    assert expand_problem(with_templates).warnings == ()
    ours = validate_problem_full(with_templates)
    theirs = validate_problem_full(without)
    assert ours.valid and theirs.valid
    assert [w.code for w in theirs.warnings] == [
        "REDUNDANT_CONSTRAINT",
        "REDUNDANT_CONSTRAINT",
        "SOFT_ALWAYS_VIOLATED",
        "CARDINALITY_FORM_AVAILABLE",
        "DUPLICATE_TERM_MERGED",
    ]
    assert ours.warnings == theirs.warnings


def test_mapped_messages_keep_the_validators_own_text():
    # The suffix is appended, never substituted: stripping it gives back the
    # message the validator wrote for the generated entry.
    candidate = problem(
        cardinality_constraint_templates=[
            {"id": "pair", "type": "hard", "for_each": ["i in item", "j in item"],
             "where": ["i < j"], "variables": ["x[i]", "x[j]"], "operator": "==", "rhs": 3}
        ]
    )  # fmt: skip
    expansion = expand_problem(candidate)
    plain = validate_problem_full(expansion.problem).errors
    mapped = validate_problem_full(candidate).errors
    assert len(plain) == len(mapped) == 3
    for before, after in zip(plain, mapped):
        assert before.path.startswith("cardinality_constraints[")
        assert after.message.startswith(before.message)
        assert re.fullmatch(
            r" \(generated by cardinality_constraint_templates\[0\] with i=\w, j=\w\)",
            after.message[len(before.message):],
        )
        assert after.recommended_action == before.recommended_action
